### PR TITLE
Adding Github Workflows

### PR DESCRIPTION
**Pull request by Alec4r**
Adding GitHub workflows with:

labeler actions: to define a size for each PR using a label.
assign by path: to add a DevOps reviewer when the PR has migrations changes.
deployments: to run the Jenkins jobs using Jenkins API.

### CODE REVIEW

**Review by diegomillan — DISMISSED** [review]

**Comment by diegomillan** [comment]
How did we choose 500 lines as a limit for the PR @Alec4r ?

**Comment by Alec4r** [comment]
> How did we choose 500 lines as a limit for the PR @Alec4r ?

I defined that because I think that we should not make larger PR's, but we can change the values.
The default value is 1000.

https://github.com/CodelyTV/pr-size-labeler/blob/master/action.yml#L22

**Comment by diegomillan** [comment]
Let's use the default then @Alec4r ...anyways would could change it in the future.

**Review by diegomillan — APPROVED** [review]

**Review by diegomillan — APPROVED** [review]

**Review by Squirrel18 — APPROVED** [review]

**Comment by Squirrel18** [comment]
Squash and rebase. @Alec4r

**Pull request merged**
